# Generated by Django 4.1.7 on 2023-04-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'managed': True, 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='students',
            table='',
        ),
    ]
