# Generated by Django 4.1.7 on 2023-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_students_options_alter_students_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='xxxxx', max_length=100)),
                ('username', models.CharField(default='xxxx', max_length=100)),
                ('password', models.CharField(default='xxxxxx', max_length=100)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='xyz@xyz.com', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='xxxxxx', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
        ),
    ]
